### ISSUE TITLE
NullPointer - Which version this plugin works ?

### ISSUE THREAD

**Issue by tiagochst** [flevet/SpineJ#1]
Hi,

I tried to run in 3 different version of imageJ in windows, but I am getting the problem shown in the image below.

Please, do you have information which imageJ version it should work ?
![SpineJ](https://user-images.githubusercontent.com/145529/102146095-68a91680-3e36-11eb-90c4-1c8aadfb2573.PNG)
 
I downloaded the last one from here: https://imagej.nih.gov/ij/download.html

Thank you!

**Comment by tiagochst** [comment]
Also on mac
<img width="698" alt="Screen Shot 2020-12-14 at 8 39 55 PM" src="https://user-images.githubusercontent.com/145529/102156930-95682880-3e4c-11eb-9e90-ec94b61283b6.png">

**Comment by flevet** [comment]
Hi,

Have you an image opened before executing SpineJ?

**Comment by tiagochst** [comment]
Thanks! That was the problem.
