### ISSUE TITLE
Error when trying to start the plugin

### ISSUE THREAD

**Issue by IzabelaJC** [flevet/SpineJ#4]
Hi all

I downloaded the .jar file and I put it in the plugins subfolder of my Fiji folder. When I start Fiji and try to select SpineJ from Plugins, I get this error every time and SpineJ doesn't start. My Fiji is up to date.
Any suggestions as to what can be wrong and how to fix it?

Thanks!
![Screenshot 2022-12-07 212543](https://user-images.githubusercontent.com/100252544/206341241-40fd9f92-1cfe-4382-b1a8-9e96a19e954a.png)

**Comment by flevet** [comment]
Hi @IzabelaJC ,

SpineJ requires to have an image first opened in Fiji/ImageJ, before executing SpineJ. Is it your case?

**Comment by IzabelaJC** [comment]
Yep, that solved the problem. Thank you!
